// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TinyTrack.Api.Data;

#nullable disable

namespace TinyTrack.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727232633_AddCaregiverSharingAndPlanTiers")]
    partial class AddCaregiverSharingAndPlanTiers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TinyTrack.Api.Features.Babies.Models.Baby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("avatar_color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("height_cm");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_babies");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_babies_guid_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_babies_user_id");

                    b.ToTable("babies", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Caregivers.Models.CaregiverAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BabyId")
                        .HasColumnType("integer")
                        .HasColumnName("baby_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("GrantedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("granted_by_user_id");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_caregiver_access");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_caregiver_access_guid_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_caregiver_access_user_id");

                    b.HasIndex("BabyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_caregiver_access_baby_id_user_id");

                    b.ToTable("caregiver_access", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Caregivers.Models.CaregiverInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<int?>("AcceptedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<int>("BabyId")
                        .HasColumnType("integer")
                        .HasColumnName("baby_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_caregiver_invites");

                    b.HasIndex("BabyId")
                        .HasDatabaseName("ix_caregiver_invites_baby_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_caregiver_invites_email");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_caregiver_invites_guid_id");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_caregiver_invites_invited_by_user_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_caregiver_invites_token");

                    b.ToTable("caregiver_invites", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Feeding.Models.FeedingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BabyId")
                        .HasColumnType("integer")
                        .HasColumnName("baby_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fed_at");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("MilkFed")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("milk_fed");

                    b.Property<decimal>("MilkPrepared")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("milk_prepared");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_feeding_logs");

                    b.HasIndex("BabyId")
                        .HasDatabaseName("ix_feeding_logs_baby_id");

                    b.HasIndex("FedAt")
                        .HasDatabaseName("idx_feeding_logs_fed_at");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_feeding_logs_guid_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_feeding_logs_user_id");

                    b.ToTable("feeding_logs", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Medications.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BabyId")
                        .HasColumnType("integer")
                        .HasColumnName("baby_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Dose")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dose");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsDoneToday")
                        .HasColumnType("boolean")
                        .HasColumnName("is_done_today");

                    b.Property<DateOnly?>("LastToggledDate")
                        .HasColumnType("date")
                        .HasColumnName("last_toggled_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_enabled");

                    b.Property<bool>("RepeatDaily")
                        .HasColumnType("boolean")
                        .HasColumnName("repeat_daily");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("time_of_day");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_medications");

                    b.HasIndex("BabyId")
                        .HasDatabaseName("ix_medications_baby_id");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_medications_guid_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_medications_user_id");

                    b.ToTable("medications", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Milestones.Models.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<int?>("BabyId")
                        .HasColumnType("integer")
                        .HasColumnName("baby_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ImagePublicId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_public_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("image_url");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("AchievedAt")
                        .HasDatabaseName("idx_milestones_achieved_at");

                    b.HasIndex("BabyId")
                        .HasDatabaseName("ix_milestones_baby_id");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_milestones_guid_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_milestones_user_id");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Pump.Models.PumpSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BabyId")
                        .HasColumnType("integer")
                        .HasColumnName("baby_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("LeftAmount")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("left_amount");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pumped_at");

                    b.Property<decimal>("RightAmount")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("right_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_pump_sessions");

                    b.HasIndex("BabyId")
                        .HasDatabaseName("ix_pump_sessions_baby_id");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_pump_sessions_guid_id");

                    b.HasIndex("PumpedAt")
                        .HasDatabaseName("idx_pump_sessions_pumped_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_pump_sessions_user_id");

                    b.ToTable("pump_sessions", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Sleep.Model.SleepingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BabyId")
                        .HasColumnType("integer")
                        .HasColumnName("baby_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsNap")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nap");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("SleepEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sleep_end");

                    b.Property<DateTime>("SleepStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sleep_start");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sleep_logs");

                    b.HasIndex("BabyId")
                        .HasDatabaseName("ix_sleep_logs_baby_id");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_sleep_logs_guid_id");

                    b.HasIndex("SleepStart")
                        .HasDatabaseName("idx_sleep_logs_sleep_start");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sleep_logs_user_id");

                    b.ToTable("sleep_logs", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Users.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("billing_cycle");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("PlanSelectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plan_selected_at");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan_tier");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_expires_at");

                    b.Property<DateTime?>("SubscriptionStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_started_at");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subscription_status");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<DateTime?>("TrialStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_started_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_guid_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Babies.Models.Baby", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_babies_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Caregivers.Models.CaregiverAccess", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Babies.Models.Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_caregiver_access_baby_baby_id");

                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_caregiver_access_user_user_id");

                    b.Navigation("Baby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Caregivers.Models.CaregiverInvite", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Babies.Models.Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_caregiver_invites_babies_baby_id");

                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_caregiver_invites_users_invited_by_user_id");

                    b.Navigation("Baby");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Feeding.Models.FeedingLog", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Babies.Models.Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_feeding_logs_baby_baby_id");

                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feeding_logs_users_user_id");

                    b.Navigation("Baby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Medications.Models.Medication", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Babies.Models.Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_medications_babies_baby_id");

                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medications_users_user_id");

                    b.Navigation("Baby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Milestones.Models.Milestone", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Babies.Models.Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_milestones_baby_baby_id");

                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_users_user_id");

                    b.Navigation("Baby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Pump.Models.PumpSession", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Babies.Models.Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pump_sessions_baby_baby_id");

                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pump_sessions_users_user_id");

                    b.Navigation("Baby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Sleep.Model.SleepingLog", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Babies.Models.Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sleep_logs_baby_baby_id");

                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sleep_logs_users_user_id");

                    b.Navigation("Baby");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
