// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TinyTrack.Api.Data;

#nullable disable

namespace TinyTrack.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621035121_AddRolesAndSubscriptions")]
    partial class AddRolesAndSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TinyTrack.Api.Features.Feeding.Models.FeedingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fed_at");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("MilkFed")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("milk_fed");

                    b.Property<decimal>("MilkPrepared")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("milk_prepared");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_feeding_logs");

                    b.HasIndex("FedAt")
                        .HasDatabaseName("idx_feeding_logs_fed_at");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_feeding_logs_guid_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_feeding_logs_user_id");

                    b.ToTable("feeding_logs", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Milestones.Models.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ImageContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_content_type");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image_data");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("AchievedAt")
                        .HasDatabaseName("idx_milestones_achieved_at");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_milestones_guid_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_milestones_user_id");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Pump.Models.PumpSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("LeftAmount")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("left_amount");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pumped_at");

                    b.Property<decimal>("RightAmount")
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("right_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_pump_sessions");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_pump_sessions_guid_id");

                    b.HasIndex("PumpedAt")
                        .HasDatabaseName("idx_pump_sessions_pumped_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_pump_sessions_user_id");

                    b.ToTable("pump_sessions", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Sleep.Model.SleepingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsNap")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nap");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("SleepEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sleep_end");

                    b.Property<DateTime>("SleepStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sleep_start");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sleep_logs");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_sleep_logs_guid_id");

                    b.HasIndex("SleepStart")
                        .HasDatabaseName("idx_sleep_logs_sleep_start");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sleep_logs_user_id");

                    b.ToTable("sleep_logs", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Users.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<Guid>("GuidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_expires_at");

                    b.Property<DateTime?>("SubscriptionStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_started_at");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subscription_status");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<DateTime?>("TrialStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_started_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GuidId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_guid_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Feeding.Models.FeedingLog", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feeding_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Milestones.Models.Milestone", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Pump.Models.PumpSession", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pump_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TinyTrack.Api.Features.Sleep.Model.SleepingLog", b =>
                {
                    b.HasOne("TinyTrack.Api.Features.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sleep_logs_users_user_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
